### ISSUE TITLE
Plugin doesn't work in 5.5.2 Confluence

### ISSUE THREAD

**Issue by dmokin** [drohne1673/confluence-survey-plugin#74] opened 2015-04-14 10:40 UTC
After installing plugin there are no any new macro has been added to macros browser. Adding {vote} or {survey} code blocks to pages have no effect. In "manage odd-ons" page the plugin and all its components are enabled.

**Comment by drohne1673** [comment] 2015-04-14 18:16
This sounds strange. Have you already tried to uninstall and reinstall the plugin again? sometimes confluences osgi container does not work correctly, that may be the case in your installation. There are several other possibilities. For a more indepth analysis i would need some technical details, like the server and confluence version used.

But uninstalling and reinstalling should do the trick for the potential hickup. All reported cases since today were of that kind. In some cases may be a confluence restart may help. These errors are very seldom and therefore almost unreproducable.

**Comment by drohne1673** [comment] 2015-05-20 21:05
closing the issue, as said cant reproduce without more intel

**Closed by drohne1673** 2015-05-20 21:05 UTC
Labels: question
